# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Colors Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$white      = rgba(ffffffff)
$gray-light = rgba(ccccccff)
$gray       = rgba(888888ff)
$gray-dark  = rgba(444444ff)
$black      = rgba(000000ff)
