# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$filemanager = nemo
$terminal = kitty
$screenshot-fullscreen = grim - | swappy -f -
$screenshot-selection = grim -g "$(slurp)" - | swappy -f -
$clipboard = ~/.config/rofi/clipboard/clipboard.sh
$powermenu = ~/.config/rofi/powermenu/powermenu.sh
$applauncher = ~/.config/rofi/launchers/launcher.sh

$idlehandler = hypridle
