# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24
envd = XDG_DATA_DIRS,/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:$HOME/.local/share
envd = QT_QPA_PLATFORMTHEME,qt5ct
envd = GTK_THEME,Adwaita:dark
