# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/0.45.0/Configuring/Monitors/


# Main monitor (1080p @ 60Hz)
monitor = HDMI-A-1, 1920x1080@100, 1920x0, 1

# Laptop monitor (1080p @ 60Hz)
monitor = eDP-1, 1920x1080@60, 0x0, 1

# Workspace rules - bind all workspaces only to main monitor
workspace = 1, monitor:HDMI-A-1, default:true
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1
workspace = 11, monitor:eDP-1
workspace = A, monitor:HDMI-A-1
workspace = B, monitor:HDMI-A-1
workspace = C, monitor:HDMI-A-1
workspace = D, monitor:HDMI-A-1
workspace = E, monitor:HDMI-A-1
workspace = F, monitor:HDMI-A-1
workspace = G, monitor:HDMI-A-1
workspace = H, monitor:HDMI-A-1
workspace = I, monitor:HDMI-A-1
workspace = J, monitor:HDMI-A-1
workspace = K, monitor:HDMI-A-1
workspace = L, monitor:HDMI-A-1
workspace = M, monitor:HDMI-A-1
workspace = N, monitor:HDMI-A-1
workspace = O, monitor:HDMI-A-1
workspace = P, monitor:HDMI-A-1
workspace = Q, monitor:HDMI-A-1
workspace = R, monitor:HDMI-A-1
workspace = S, monitor:HDMI-A-1
workspace = T, monitor:HDMI-A-1
workspace = U, monitor:HDMI-A-1
workspace = V, monitor:HDMI-A-1
workspace = W, monitor:HDMI-A-1
workspace = X, monitor:HDMI-A-1
workspace = Y, monitor:HDMI-A-1
workspace = Z, monitor:HDMI-A-1

# If you need to scale things like steam etc, please uncomment these lines.
# Adjust GDK_SCALE accordingly to your liking.
#xwayland {
#  force_zero_scaling = true       # Unscale XWayland
#}

#env = GDK_SCALE, 1.25             # GDK Scaling Factor
